/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.*;
import  DTO.*;
import java.awt.Dimension;
import java.awt.Toolkit;
//import com.sun.javafx.scene.layout.region.Margins;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Huyen
 */
public class ThemKH extends javax.swing.JFrame {

    /**
     * Creates new form YC8Frame
     */
    BUS_ThemKH bus_ThemKH;
    BUS_TimKH bus_TimKH;
    ButtonGroup btgGioiTinh;
    String GioiTinh;
    String NgaySinh;
    String DieuKien;
    String CMNDcu;
    int index;
    boolean Exist = false;
    ArrayList <String> LoaiKhachHang = new ArrayList<String>();
    String [] Header ={"Mã khách hàng", "Mã loại khách", "Họ tên","Giới tính", "Ngày sinh", "CMND", "Địa chỉ","SĐT","Email"}; 
    DefaultTableModel dtm = new DefaultTableModel(Header,0);
    public static ArrayList <DTO_KhachHang> DSKhachHang = new ArrayList<DTO_KhachHang>();
    public ThemKH() {
        initComponents();
        Init();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Init()
    {              
        tbTim.setModel(dtm);
        bus_ThemKH = new BUS_ThemKH();
        bus_TimKH = new BUS_TimKH();
        try {
             LoaiKhachHang = bus_ThemKH.getLoaiKhachHang();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        for (int i=0; i<LoaiKhachHang.size();i++)
        {
            cbLoaiKH.addItem(LoaiKhachHang.get(i));
        }
        DieuKien="cmnd";        
        btgGioiTinh = new ButtonGroup();
        btgGioiTinh.add(rbNam);
        btgGioiTinh.add(rbNu);
        btgGioiTinh.add(rbKhac);
    }
    void Reset()
    {
        tfCMND.setText("");
        tfSDT.setText("");
        cbLoaiKH.setSelectedItem(null);
        tfEmail.setText("");
        tfDiaChi.setText("");
        tfHoTen.setText("");        
        tfMaKH.setText(tfCMND.getText());
        rbKhac.setSelected(false);
        rbNam.setSelected(false);
        rbNu.setSelected(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbTim = new javax.swing.JComboBox<>();
        tfChiTiet = new javax.swing.JTextField();
        btTim = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTim = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        pnThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfMaKH = new java.awt.TextField();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        rbNu = new javax.swing.JRadioButton();
        rbKhac = new javax.swing.JRadioButton();
        rbNam = new javax.swing.JRadioButton();
        dcNgaySinh = new com.toedter.calendar.JDateChooser();
        tfHoTen = new javax.swing.JTextField();
        tfCMND = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        cbLoaiKH = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btThuePhong = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(203, 234, 237));

        jPanel1.setBackground(new java.awt.Color(211, 219, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CMND", "Họ tên", "SĐT" }));
        cbTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTimActionPerformed(evt);
            }
        });

        btTim.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btTim.setText("Tìm");
        btTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTimMouseClicked(evt);
            }
        });

        tbTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTimMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTim);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TÌM KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTim)
                        .addGap(196, 196, 196))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(173, 228, 152));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DANH SÁCH KHÁCH THUÊ");

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Giới tính", "Ngày sinh", "CMND", "Địa chỉ", "Email", "Loại khách", "SĐT"
            }
        ));
        tbKhachHang.setColumnSelectionAllowed(true);
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhachHang);
        tbKhachHang.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbKhachHang.getColumnModel().getColumnCount() > 0) {
            tbKhachHang.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnThongTin.setBackground(new java.awt.Color(255, 255, 221));
        pnThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã khách hàng:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("CMND:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Địa chỉ:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("SĐT:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Loại khách hàng:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Giới tính:");

        tfMaKH.setEnabled(false);
        tfMaKH.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("THÔNG TIN KHÁCH HÀNG");

        rbNu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbNu.setText("Nữ");

        rbKhac.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbKhac.setText("Khác");

        rbNam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbNam.setText("Nam");

        dcNgaySinh.setDateFormatString("dd-MM-yyyy");

        tfCMND.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCMNDKeyPressed(evt);
            }
        });

        tfSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSDTKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTinLayout.createSequentialGroup()
                        .addComponent(rbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbKhac)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(tfMaKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfHoTen)
                    .addComponent(dcNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCMND, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(103, 103, 103)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSDT)
                            .addComponent(tfEmail)
                            .addComponent(tfDiaChi)
                            .addComponent(cbLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                        .addComponent(btThem)
                        .addGap(18, 18, 18)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(rbNu)
                    .addComponent(rbKhac)
                    .addComponent(rbNam)
                    .addComponent(cbLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(dcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(btThem)
                    .addComponent(btSua)
                    .addComponent(btXoa)
                    .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(240, 236, 227));

        jLabel7.setBackground(new java.awt.Color(89, 110, 121));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(89, 110, 121));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LẤY THÔNG TIN KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        btThuePhong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btThuePhong.setText("LẬP PHIẾU THUÊ PHÒNG");
        btThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThuePhongMouseClicked(evt);
            }
        });
        btThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThuePhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btThuePhong)
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 662, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
       // if ()
       if (rbKhac.isSelected())
           GioiTinh="Khác";
       if (rbNam.isSelected())
           GioiTinh="Nam";
       if (rbNu.isSelected())
           GioiTinh="Nữ";
       NgaySinh = String.format("%1$td-%1$tm-%1$tY", dcNgaySinh.getDate());  
       tfMaKH.setText(tfCMND.getText());
       if (DSKhachHang.size()==bus_ThemKH.SoKhachToiDa())
           JOptionPane.showMessageDialog(null, "Vượt quá số khách tối đa.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
       else
       if (tfMaKH.getText().length()>0&&tfHoTen.getText().length()>0&&tfCMND.getText().length()>0&&tfEmail.getText().length()>0&&tfSDT.getText().length()>0&&tfDiaChi.getText().length()>0&&cbLoaiKH.getSelectedItem().toString().length()>0&&NgaySinh.length()>0&& GioiTinh.length()>0)
       {
           DTO_KhachHang dto = new DTO_KhachHang(tfMaKH.getText(), cbLoaiKH.getSelectedItem().toString(), tfHoTen.getText(), GioiTinh, NgaySinh, tfCMND.getText(), tfDiaChi.getText(),tfSDT.getText(), tfEmail.getText(),  true);           
           if (Exist)
           {
               if (check(tfCMND.getText()))
               {
                   DSKhachHang.add(dto);
                   ThemKH();
                   Exist=false;
               }
               else
                   JOptionPane.showMessageDialog(null, "Đã có trong danh sách khách thuê rồi", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }
           else
           {
            
            int rs = bus_ThemKH.Add(dto);
           if (rs>0)
           {
               DSKhachHang.add(dto);
               ThemKH();
               JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }
           else
               JOptionPane.showMessageDialog(null, "Không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           }
           
       }
       
        Reset();
    }//GEN-LAST:event_btThemActionPerformed
    public void ThemKH()
    {
        dtm = new DefaultTableModel(Header,0);
        for (int i=0; i<DSKhachHang.size();i++)
        {
            Vector data = new Vector();
        data.add(DSKhachHang.get(i).getMaKhachHang());
        data.add(DSKhachHang.get(i).getMaLoaiKhachHang());
        data.add(DSKhachHang.get(i).getHoTen()); 
        data.add(DSKhachHang.get(i).getGioiTinh());
        data.add(DSKhachHang.get(i).getNgaySinh());
        data.add(DSKhachHang.get(i).getCMND());
        data.add(DSKhachHang.get(i).getDiaChi());
        data.add(DSKhachHang.get(i).getSDT());
        data.add(DSKhachHang.get(i).getEmail());
        dtm.addRow(data);
        }
        tbKhachHang.setModel(dtm);
    }
    public boolean check(String CMND) 
    {
        for (int i=0; i<DSKhachHang.size();i++)
        {
            if (DSKhachHang.get(i).getCMND().equals(CMND))
                return false;
        }
        return true;
    }
    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        if (rbKhac.isSelected())
           GioiTinh="Khác";
       if (rbNam.isSelected())
           GioiTinh="Nam";
       if (rbNu.isSelected())
           GioiTinh="Nữ";
       JOptionPane.showMessageDialog(null, CMNDcu,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
       NgaySinh = String.format("%1$td-%1$tm-%1$tY", dcNgaySinh.getDate());          
       tfMaKH.setText(tfCMND.getText());
       if (tfMaKH.getText().length()>0&&tfHoTen.getText().length()>0&&tfCMND.getText().length()>0&&tfEmail.getText().length()>0&&tfSDT.getText().length()>0&&tfDiaChi.getText().length()>0&&cbLoaiKH.getSelectedItem().toString().length()>0&&NgaySinh.length()>0&& GioiTinh.length()>0)
       {
           DTO_KhachHang dto = new DTO_KhachHang(tfMaKH.getText(), cbLoaiKH.getSelectedItem().toString(), tfHoTen.getText(), GioiTinh, NgaySinh, tfCMND.getText(), tfDiaChi.getText(), tfEmail.getText(), tfSDT.getText(), true);
           DSKhachHang.add(index, dto);
           DSKhachHang.remove(+1);
           int rs = bus_ThemKH.Update(dto, CMNDcu);
           if (rs>0)
               JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           else
               JOptionPane.showMessageDialog(null, "Không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
       }
        ThemKH();
        Reset();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:       
        tfMaKH.setText(tfCMND.getText());
        int rs = bus_ThemKH.Delete(tfMaKH.getText());
        DSKhachHang.remove(index);
        if (rs>0)
               JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           else
               JOptionPane.showMessageDialog(null, "Không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        Reset();
        ThemKH();
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseClicked
        // TODO add your handling code here:
        index = tbKhachHang.getSelectedRow();
        tfMaKH.setText(tbKhachHang.getValueAt(index, 0).toString());
        cbLoaiKH.setSelectedItem(tbKhachHang.getValueAt(index, 1).toString());
        tfHoTen.setText(tbKhachHang.getValueAt(index, 2).toString());
        GioiTinh=tbKhachHang.getValueAt(index, 3).toString();
        if (GioiTinh.equals("Khác"))
            rbKhac.setSelected(true);
        if (GioiTinh.equals("Nam"))
            rbNam.setSelected(true);
        if (GioiTinh.equals("Nữ"))
            rbNu.setSelected(true);
        NgaySinh=(tbKhachHang.getValueAt(index, 4).toString());
        DateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        try {
            dcNgaySinh.setDate(date.parse(NgaySinh));
        } catch (ParseException ex) {
            Logger.getLogger(ThemKH.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfCMND.setText(tbKhachHang.getValueAt(index, 5).toString());
        tfDiaChi.setText(tbKhachHang.getValueAt(index, 6).toString());
        tfSDT.setText(tbKhachHang.getValueAt(index, 7).toString());
        tfEmail.setText(tbKhachHang.getValueAt(index, 8).toString());        
        CMNDcu= tfCMND.getText();
    }//GEN-LAST:event_tbKhachHangMouseClicked

    private void cbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTimActionPerformed
        // TODO add your handling code here:
        DieuKien= cbTim.getSelectedItem().toString();
        if (DieuKien.equals("Họ tên"))
        DieuKien="hoten";
        if (DieuKien.equals("SĐT"))
        DieuKien="sdt";
    }//GEN-LAST:event_cbTimActionPerformed

    private void btTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTimMouseClicked
        // TODO add your handling code here:

        if (bus_TimKH.TimKH(DieuKien, tfChiTiet.getText())==null)
        JOptionPane.showMessageDialog(null,"Không thấy","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else
        tbTim.setModel(bus_TimKH.TimKH(DieuKien, tfChiTiet.getText()));
    }//GEN-LAST:event_btTimMouseClicked

    private void tbTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTimMouseClicked
        // TODO add your handling code here:
        index = tbTim.getSelectedRow();
        tfMaKH.setText(tbTim.getValueAt(index, 0).toString());
        cbLoaiKH.setSelectedItem(tbTim.getValueAt(index, 1).toString());
        tfHoTen.setText(tbTim.getValueAt(index, 2).toString());
        GioiTinh=tbTim.getValueAt(index, 3).toString();
        if (GioiTinh.equals("Khác"))
            rbKhac.setSelected(true);
        if (GioiTinh.equals("Nam"))
            rbNam.setSelected(true);
        if (GioiTinh.equals("Nữ"))
            rbNu.setSelected(true);
        NgaySinh=(tbTim.getValueAt(index, 4).toString());
        DateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        try {
            dcNgaySinh.setDate(date.parse(NgaySinh));
        } catch (ParseException ex) {
            Logger.getLogger(ThemKH.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfCMND.setText(tbTim.getValueAt(index, 5).toString());
        tfDiaChi.setText(tbTim.getValueAt(index, 6).toString());
        tfSDT.setText(tbTim.getValueAt(index, 7).toString());
        tfEmail.setText(tbTim.getValueAt(index, 8).toString());
        CMNDcu=tfCMND.getText();
        Exist=true;
    }//GEN-LAST:event_tbTimMouseClicked

    private void tfCMNDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCMNDKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && (evt.getKeyChar()) <= '9' &&tfCMND.getText().length()<9)||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar() ==KeyEvent.VK_DELETE)
        {
            if (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE  || evt.getKeyChar() ==KeyEvent.VK_DELETE)
            {
                String S = tfCMND.getText();
                tfCMND.setText(S.substring(0, S.length()-1));
            }
               tfCMND.setEditable(true);
        } else 
        {
            tfCMND.setEditable(false); 
            JOptionPane.showMessageDialog(null,"Số CMND tối đa là 9 chữ số ", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tfCMNDKeyPressed

    private void tfSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSDTKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= '0' && (evt.getKeyChar()) <= '9' &&tfSDT.getText().length()<10)||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE || evt.getKeyChar() ==KeyEvent.VK_DELETE)
        {
            if (evt.getKeyChar()==KeyEvent.VK_BACK_SPACE  || evt.getKeyChar() ==KeyEvent.VK_DELETE)
            {
                String S = tfSDT.getText();
                tfSDT.setText(S.substring(0, S.length()-1));
            }
               tfSDT.setEditable(true);
        } else 
        {tfSDT.setEditable(false); JOptionPane.showMessageDialog(null,"Số điện thoại tối đa là 10 chữ số ", "Thông báo",JOptionPane.INFORMATION_MESSAGE);}
        
    }//GEN-LAST:event_tfSDTKeyPressed

    private void btThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThuePhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btThuePhongActionPerformed

    private void btThuePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThuePhongMouseClicked
        // TODO add your handling code here:
        this.dispose();
        YC2Form yc2 = new YC2Form();
        yc2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        yc2.setVisible(true);
    }//GEN-LAST:event_btThuePhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus_ThemKH look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus_ThemKH (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus_ThemKH".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThuePhong;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbLoaiKH;
    private javax.swing.JComboBox<String> cbTim;
    private com.toedter.calendar.JDateChooser dcNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JRadioButton rbKhac;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTable tbTim;
    private javax.swing.JTextField tfCMND;
    private javax.swing.JTextField tfChiTiet;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHoTen;
    private java.awt.TextField tfMaKH;
    private javax.swing.JTextField tfSDT;
    // End of variables declaration//GEN-END:variables
}
