/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
/**
 *
 * @author Huyen
 */

import DTO.*;
import  BUS.*;
//import com.sun.javafx.scene.layout.region.Margins;
//import com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.awt.*;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.NumberFormat;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
//import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class YC2Form extends javax.swing.JFrame {
    DTO_Phong Phong;
    BUS_YC2 bus = new BUS_YC2();
    BUS_ThemKH bus_ThemKH = new BUS_ThemKH();
    LocalDate lcd = LocalDate.now();
    LocalTime lct = LocalTime.now();
    String s="";
    float DonGia;
    String MaPhong;
    int SoKhachToiDa;
    float TyLePhuThu;
    /**
     * Creates new form YC2Form
     */
    public YC2Form() {
        initComponents(); 
        Init();
        
    }
    void Reset()
    {
        tfMaPTP.setText(String.valueOf(bus.MaPTP()));
        cbMaPhong.setSelectedItem(1);
        cbHinhThucThue.setSelectedItem(1);
        tfNgayThue.setText(lcd.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        tfGioBatDauThue.setText(lct.format(DateTimeFormatter.ofPattern("hh:mm a")));
        tfSoKhach.setText("");
        tfDonGiaThue.setText("");
        tfDonGiaTieuChuan.setText("");
        tfSoKhach.setText(String.valueOf(ThemKH.DSKhachHang.size()));
        String [] Header ={"Mã loại khách", "Họ tên","CMND", "Địa chỉ"}; 
        DefaultTableModel dtm = new DefaultTableModel(Header,0);
        tbKhachThue.setModel(dtm);
    }
    void Init()
    {
        this.setLocationRelativeTo(null);
        loadData();
        int tam = bus.MaPTP();
        SoKhachToiDa = bus.SoKhachToiDa();
        tfMaPTP.setText(Integer.toString(tam));
        tfNgayThue.setText(lcd.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        tfGioBatDauThue.setText(lct.format(DateTimeFormatter.ofPattern("hh:mm a")));
        ArrayList <String> DanhSachPhong = bus.getDanhSachPhongTrong();
        for (int i=0; i<DanhSachPhong.size(); i++)
        {
            if (DanhSachPhong.get(i)!=null)
            cbMaPhong.addItem(DanhSachPhong.get(i));
        }
        ArrayList <String> DanhSachHinhThucThue = bus.getDanhSachHinhThuc();
        for (int i=0; i<DanhSachHinhThucThue.size();i++)
        {
            if (DanhSachHinhThucThue.get(i)!=null)
                cbHinhThucThue.addItem(DanhSachHinhThucThue.get(i));
        }
        GetDSKhachHang1();
        float DonGiaTieuChuan=bus.GetDonGia(cbMaPhong.getItemAt(0));
        tfDonGiaTieuChuan.setText(String.valueOf(DonGiaTieuChuan));
        tfDonGiaThue.setText(String.valueOf(DonGiaTieuChuan*(1+TyLePhuThu)));
        tfSoKhach.setText(String.valueOf(ThemKH.DSKhachHang.size()));
}
    public void GetDSKhachHang1()
    {
        String [] Header ={"Mã loại khách", "Họ tên","CMND", "Địa chỉ"}; 
        DefaultTableModel dtm = new DefaultTableModel(Header,0);
        dtm.setRowCount(0);
        DTO_KhachHang dto = new DTO_KhachHang();
        for (int i=0; i<ThemKH.DSKhachHang.size();i++)
        {
            dto=ThemKH.DSKhachHang.get(i);
            String maLoaiKH = dto.getMaLoaiKhachHang();
            TyLePhuThu+=bus.GetHeSoPhuThu(dto.getMaLoaiKhachHang());
            String hoten = dto.getHoTen();
            String CMND = dto.getCMND();
            String DiaChi = dto.getDiaChi();
            Object [] row = {maLoaiKH, hoten, CMND,DiaChi};
            dtm.addRow(row);
        }
            tbKhachThue.setModel(dtm);
            if (ThemKH.DSKhachHang.size()>bus.GetSoKhachKhongPhuThu())
                TyLePhuThu+=(ThemKH.DSKhachHang.size()-bus.GetSoKhachKhongPhuThu())*bus.GetTiLePhuThuTheoSoKhach();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbThongTin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachThue = new javax.swing.JTable();
        pnDanhSach = new javax.swing.JPanel();
        lbDanhSach = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        pnThongTin = new javax.swing.JPanel();
        lbMaPTP = new javax.swing.JLabel();
        lbGioBatDauThue = new javax.swing.JLabel();
        lbMaPhong = new javax.swing.JLabel();
        lbHinhThucThue = new javax.swing.JLabel();
        lbDonGiaTieuChuan = new javax.swing.JLabel();
        lbSoKhach = new javax.swing.JLabel();
        lbDonGiaThue = new javax.swing.JLabel();
        lbNgayBatDauThue = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        tfMaPTP = new javax.swing.JTextField();
        tfDonGiaThue = new javax.swing.JTextField();
        tfDonGiaTieuChuan = new javax.swing.JTextField();
        tfGioBatDauThue = new javax.swing.JTextField();
        tfNgayThue = new javax.swing.JTextField();
        cbHinhThucThue = new javax.swing.JComboBox<>();
        cbMaPhong = new javax.swing.JComboBox<>();
        tfSoKhach = new javax.swing.JTextField();
        lbThongTin1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(203, 234, 237));

        jPanel1.setBackground(new java.awt.Color(211, 219, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbThongTin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbThongTin.setForeground(new java.awt.Color(204, 0, 0));
        lbThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongTin.setText("DANH SÁCH KHÁCH THUÊ");

        tbKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbKhachThue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        pnDanhSach.setBackground(new java.awt.Color(173, 228, 152));
        pnDanhSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbDanhSach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDanhSach.setForeground(new java.awt.Color(204, 0, 0));
        lbDanhSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDanhSach.setText("DANH SÁCH PHIẾU THUÊ PHÒNG");

        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu thuê", "Mã phòng", "Mã khách", "Hình thức thuê", "Giờ thuê", "Ngày thuê", "Số khách", "Đơn giá thuê", "Đơn giá tiêu chuẩn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDanhSach.setColumnSelectionAllowed(true);
        tbDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDanhSach);
        tbDanhSach.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tbDanhSach.getColumnModel().getColumnCount() > 0) {
            tbDanhSach.getColumnModel().getColumn(0).setPreferredWidth(120);
            tbDanhSach.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbDanhSach.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbDanhSach.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbDanhSach.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbDanhSach.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbDanhSach.getColumnModel().getColumn(6).setPreferredWidth(80);
            tbDanhSach.getColumnModel().getColumn(7).setPreferredWidth(120);
            tbDanhSach.getColumnModel().getColumn(8).setPreferredWidth(150);
        }

        javax.swing.GroupLayout pnDanhSachLayout = new javax.swing.GroupLayout(pnDanhSach);
        pnDanhSach.setLayout(pnDanhSachLayout);
        pnDanhSachLayout.setHorizontalGroup(
            pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnDanhSachLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnDanhSachLayout.setVerticalGroup(
            pnDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pnThongTin.setBackground(new java.awt.Color(255, 255, 221));
        pnThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbMaPTP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMaPTP.setText("Mã phiếu thuê phòng:");

        lbGioBatDauThue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbGioBatDauThue.setText("Giờ bắt đầu thuê:");

        lbMaPhong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMaPhong.setText("Mã phòng:");

        lbHinhThucThue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbHinhThucThue.setText("Hình thức thuê:");

        lbDonGiaTieuChuan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDonGiaTieuChuan.setText("Đơn giá tiêu chuẩn:");

        lbSoKhach.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoKhach.setText("Số khách:");

        lbDonGiaThue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDonGiaThue.setText("Đơn giá thuê:");

        lbNgayBatDauThue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNgayBatDauThue.setText("Ngày bắt đầu thuê:");

        btThem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        tfMaPTP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfMaPTP.setEnabled(false);
        tfMaPTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaPTPActionPerformed(evt);
            }
        });

        tfDonGiaThue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tfDonGiaTieuChuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tfGioBatDauThue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tfNgayThue.setEditable(false);

        cbHinhThucThue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        cbMaPhong.setMaximumRowCount(1000);
        cbMaPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaPhongItemStateChanged(evt);
            }
        });

        tfSoKhach.setEnabled(false);

        lbThongTin1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbThongTin1.setForeground(new java.awt.Color(204, 0, 0));
        lbThongTin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongTin1.setText("THÔNG TIN PHIẾU THUÊ PHÒNG");

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinLayout.createSequentialGroup()
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaPhong)
                            .addComponent(lbMaPTP)
                            .addComponent(lbHinhThucThue)
                            .addComponent(lbGioBatDauThue))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbMaPhong, 0, 111, Short.MAX_VALUE)
                                .addComponent(tfMaPTP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbHinhThucThue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfGioBatDauThue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                                .addComponent(lbDonGiaTieuChuan)
                                .addGap(18, 18, 18)
                                .addComponent(tfDonGiaTieuChuan, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnThongTinLayout.createSequentialGroup()
                                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbSoKhach)
                                            .addComponent(lbDonGiaThue))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThongTinLayout.createSequentialGroup()
                                        .addComponent(lbNgayBatDauThue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSoKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(tfDonGiaThue)))))
                    .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbThongTin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                        .addComponent(btThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoa)
                        .addGap(18, 18, 18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinLayout.createSequentialGroup()
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaPTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMaPTP))
                        .addGap(11, 11, 11)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaPhong)
                            .addComponent(cbMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbHinhThucThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHinhThucThue))
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(tfGioBatDauThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbGioBatDauThue))))
                    .addGroup(pnThongTinLayout.createSequentialGroup()
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNgayBatDauThue))
                        .addGap(11, 11, 11)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoKhach)
                            .addComponent(tfSoKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbDonGiaThue)
                            .addComponent(tfDonGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbDonGiaTieuChuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDonGiaTieuChuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btSua)
                    .addComponent(btXoa))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 236, 227));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 110, 121));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU THUÊ PHÒNG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(pnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 671, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                    .addComponent(pnDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        
       if (tfMaPTP.getText().length()>0 && cbMaPhong.getSelectedItem().toString().length()>0 && cbHinhThucThue.getSelectedItem().toString().length()>0 && tfGioBatDauThue.getText().length()>0 && tfNgayThue.getText().length()>0&& tfSoKhach.getText().length()>0&& tfDonGiaThue.getText().length()>0 && tfDonGiaTieuChuan.getText().length()>0)
        {
            int sk=Integer.parseInt(tfSoKhach.getText());
            float dgt=Float.parseFloat(tfDonGiaThue.getText());
            float dgtc=Float.parseFloat(tfDonGiaTieuChuan.getText());
            
            DTO_PhieuThuePhong dto = new DTO_PhieuThuePhong(tfMaPTP.getText(), cbMaPhong.getSelectedItem().toString(), cbHinhThucThue.getSelectedItem().toString(), tfGioBatDauThue.getText(), tfNgayThue.getText(),sk, dgt, dgtc, true, false );
            if (bus.checkPhong(cbMaPhong.getSelectedItem().toString()))
            {
                int result = bus.Add(dto);
                if (result>0)
                {
                    ThemCT_PTP();
                    JOptionPane.showMessageDialog(null,"Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
                JOptionPane.showMessageDialog(null,"Phòng đang được thuê", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Cần nhập đầy đủ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadData();
        int re = bus.UpdatePhong(cbMaPhong.getSelectedItem().toString(), "Đang thuê");
        Reset();
    }//GEN-LAST:event_btThemActionPerformed
    private void ThemCT_PTP()
            {
                int re=0;
        for (int i=0; i<ThemKH.DSKhachHang.size();i++)
        {
            int rs = bus_ThemKH.Add_CT(String.valueOf(bus_ThemKH.MaPTP()), ThemKH.DSKhachHang.get(i).getHoTen(),ThemKH.DSKhachHang.get(i).getMaLoaiKhachHang(), ThemKH.DSKhachHang.get(i).getCMND(),ThemKH.DSKhachHang.get(i).getDiaChi(), true);
            if (rs>0)
                re++;
        }    
        if (re== ThemKH.DSKhachHang.size())
            JOptionPane.showMessageDialog(null, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           else
               JOptionPane.showMessageDialog(null, "Không thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
    
    private void tfMaPTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaPTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaPTPActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
         if (tfMaPTP.getText().length()>0 && cbMaPhong.getSelectedItem().toString().length()>0 && cbHinhThucThue.getSelectedItem().toString().length()>0 && tfGioBatDauThue.getText().length()>0 && tfNgayThue.getText().length()>0&& tfSoKhach.getText().length()>0&& tfDonGiaThue.getText().length()>0 && tfDonGiaTieuChuan.getText().length()>0)
        {
            int sk = Integer.parseInt(tfSoKhach.getText());
            float dgt = Float.parseFloat(tfDonGiaThue.getText());
            float dgtc = Float.parseFloat(tfDonGiaTieuChuan.getText());
            DTO_PhieuThuePhong dto = new DTO_PhieuThuePhong(tfMaPTP.getText(), cbMaPhong.getSelectedItem().toString(), cbHinhThucThue.getSelectedItem().toString(), tfGioBatDauThue.getText(), tfNgayThue.getText(),sk, dgt, dgtc, true , false);
            int result = bus.Update(dto);
            if (result>0)
            {
                JOptionPane.showMessageDialog(null,"Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                bus.UpdatePhong(MaPhong, "Trống");
                bus.UpdatePhong(cbMaPhong.getSelectedItem().toString(), "Được thuê");
                Reset();
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Cần nhập đầy đủ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
         
        loadData();
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int result=bus.Delete(tfMaPTP.getText());
        if (result>0)
        {
            JOptionPane.showMessageDialog(null,"Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            bus.UpdatePhong(MaPhong, "Trống");
            Reset();
    }
        loadData();
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachMouseClicked
        // TODO add your handling code here:
        int Index = tbDanhSach.getSelectedRow();
            tfMaPTP.enable(true);
            tfMaPTP.setText(tbDanhSach.getValueAt(Index, 0).toString());
            cbMaPhong.setSelectedItem(tbDanhSach.getValueAt(Index, 1).toString());
            cbHinhThucThue.setSelectedItem(tbDanhSach.getValueAt(Index, 2));
            tfGioBatDauThue.setText(tbDanhSach.getValueAt(Index, 3).toString());
            tfNgayThue.setText(tbDanhSach.getValueAt(Index, 4).toString());
            tfSoKhach.setText(tbDanhSach.getValueAt(Index, 5).toString());
            tfDonGiaThue.setText(tbDanhSach.getValueAt(Index, 6).toString());   
            tfDonGiaTieuChuan.setText(tbDanhSach.getValueAt(Index, 7).toString());
            tfMaPTP.enable(false);
            MaPhong=cbMaPhong.getSelectedItem().toString();
            tbKhachThue.setModel(bus.getDachSachKhachThue(tfMaPTP.getText()));
    }//GEN-LAST:event_tbDanhSachMouseClicked

    private void cbMaPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaPhongItemStateChanged
        // TODO add your handling code here:
        DonGia = bus.GetDonGia(cbMaPhong.getSelectedItem().toString());
        tfDonGiaTieuChuan.setText(String.valueOf(DonGia));
        tfDonGiaThue.setText(String.valueOf(DonGia*(1+TyLePhuThu)));
    }//GEN-LAST:event_cbMaPhongItemStateChanged
    public void loadData()
    {        
        String [] Header = {"Mã phiếu thuê", "Mã phòng","Hình thức thuê", "Giờ bắt đầu thuê", "Ngày bắt đầu thuê", "Số khách", "Đơn giá tiêu chuẩn", "Đơn giá thuê "};
        DefaultTableModel dtm = new DefaultTableModel(Header, 0);
        ArrayList <DTO_PhieuThuePhong> arr = new ArrayList<DTO_PhieuThuePhong>();
        BUS_YC2 bu = new BUS_YC2();
        arr= bu.getData();
        dtm.setRowCount(0);
        DTO_PhieuThuePhong dto = new DTO_PhieuThuePhong();
        for (int i=0; i<arr.size();i++)
        {
            dto=arr.get(i);
            String maptp = dto.getMaPTP();
            String maphong = dto.getMaPhong();
            String mahinhthuc = dto.getMaHinhThuc();
            String giothue = dto.getGioBatDauThue();
            String ngaythue = dto.getNgayBatDauThue();
            int sk = dto.getSoKhach();
            float dgt = dto.getDonGiaThue();
            float dgtc = dto.getDonGiaTieuChuan();
            Object [] row = {maptp,maphong,mahinhthuc,giothue,ngaythue,sk,dgt,dgtc};
            dtm.addRow(row);
        }
            tbDanhSach.setModel(dtm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YC2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YC2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YC2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YC2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YC2Form().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbHinhThucThue;
    private javax.swing.JComboBox<String> cbMaPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDanhSach;
    private javax.swing.JLabel lbDonGiaThue;
    private javax.swing.JLabel lbDonGiaTieuChuan;
    private javax.swing.JLabel lbGioBatDauThue;
    private javax.swing.JLabel lbHinhThucThue;
    private javax.swing.JLabel lbMaPTP;
    private javax.swing.JLabel lbMaPhong;
    private javax.swing.JLabel lbNgayBatDauThue;
    private javax.swing.JLabel lbSoKhach;
    private javax.swing.JLabel lbThongTin;
    private javax.swing.JLabel lbThongTin1;
    private javax.swing.JPanel pnDanhSach;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JTable tbDanhSach;
    private javax.swing.JTable tbKhachThue;
    private javax.swing.JTextField tfDonGiaThue;
    private javax.swing.JTextField tfDonGiaTieuChuan;
    private javax.swing.JTextField tfGioBatDauThue;
    private javax.swing.JTextField tfMaPTP;
    private javax.swing.JTextField tfNgayThue;
    private javax.swing.JTextField tfSoKhach;
    // End of variables declaration//GEN-END:variables
}
